### PR TITLE
fix(ui_localizations): loading Traditional Chinese

### LINKED ISSUE #33: 🐛 [firebase_ui_localizations] Traditional Chinese is not loading
Traditional Chinese will not be loaded in Firebase UI Auth using the standard locales as described [here](https://docs.flutter.dev/development/accessibility-and-localization/internationalization#advanced-locale-definition). (Simplified Chinese can be properly loaded).

This issue is caused by the non-standard key `zh_tw` In /lib/src/all_languages.dart (see below). It should have been `zh_TW`.

```
final localizations = <String, FirebaseUILocalizationLabels>{
  ...
  'zh': const ZhLocalizations(),
  'zh_tw': const ZhTWLocalizations(),
  ...
};
```

I suggest the following fix to match the standard given by Flutter in the previous URL.

In /lib/src/all_languages.dart:
```
final localizations = <String, FirebaseUILocalizationLabels>{
  ...
  'zh': const ZhLocalizations(), // Simplified Chinese
  'zh_Hans': const ZhLocalizations(), // Simplified Chinese
  'zh_Hant': const ZhTWLocalizations(), // Traditional Chinese
  'zh_Hans_CN': const ZhLocalizations(), // Simplified Chinese
  'zh_Hant_TW': const ZhTWLocalizations(), // Traditional Chinese
  'zh_Hant_HK': const ZhTWLocalizations(), // Traditional Chinese
  ...
};
```

In /lib/src/l10n.dart:

```
@override
  Future<FirebaseUILocalizations> load(Locale locale) {
    late FirebaseUILocalizationLabels labels;

    final key = locale.languageCode;
    // Change this line to include script code
    final scriptCode = locale.scriptCode;
    final countryCode = locale.countryCode;
    var fullKey = key;

    scriptCode != null ? fullKey += '_$scriptCode' : null;
    countryCode != null ? fullKey += '_$countryCode' : null;
    ...
  }
```

### PR DESCRIPTION
**Pull request by gary6lin**
## Description

I found that the `firebase_ui_localizations` package includes a translation for Taiwan (`ZhTWLocalizations`), but has not been used appropriately. So I follow the same approach of how the `flutter_localizations` package gets the appropriate translation and how to fallback when the `scriptCode` or `countryCode` is not defined.

## Related Issues

Closes #33 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] All unit tests pass (`melos run test:unit:all` doesn't fail).
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is _not_ a breaking change.

[issue database]: https://github.com/firebase/FirebaseUI-Flutter/issues
[Contributor Guide]: https://github.com/firebase/FirebaseUI-Flutter/blob/main/docs/contributing.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_ui_localizations/lib/src/all_languages.dart [hunk 1]
```diff
@@ -1,52 +1,119 @@
...
+  'pt', // Portuguese
+  'ru', // Russian
+  'th', // Thai
+  'tr', // Turkish
+  'uk', // Ukrainian
+  'zh', // Chinese
 };
+
+FirebaseUILocalizationLabels getFirebaseUITranslation(Locale useLocale,
+    [Locale? defaultLocale]) {
```
Comment (lesnitsky) [inline packages/firebase_ui_localizations/lib/src/all_languages.dart:54]: add trailing comma

**Review by lesnitsky — CHANGES_REQUESTED** [review]

**Comment by lesnitsky** [comment]
@gary6lin Thanks for submitting a PR! Could you please add unit tests verifying that traditional Chinese loads correctly now?  Also might be good to add a test verifying that localization overrides still work.

**Comment by gary6lin** [comment]
Trailing comma and test cases added.

**Review by lesnitsky — APPROVED** [review]

File: packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    'FirebaseUILocalization loads the appropriate Chinese translation',
+    () {
+      setUp(() async {
+        delegate = const FirebaseUILocalizationDelegate();
+      });
+
+      test(
+        'Loads the correct translation with the language tag "${localeZh.toLanguageTag()}"',
+        () async {
+          final localizations = await delegate.load(localeZh);
```
Comment (lesnitsky) [inline packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart:26]: could we have a widget test here instead? So something along these lines:

```
testWidgets('...', (tester) async {
  await tester.pumpWidget(
    MaterialApp(
      locale: Locale('zh'),
      ...
    )
  );
  
  expect(find.text('some translated label'), expected);
});

// same test, but for `zh-tw`

// widget test for label overrides

**Review by lesnitsky — CHANGES_REQUESTED** [review]

File: packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+  const ZhTWLocalizationsOverrides();
+
+  @override
+  String get verifyEmailTitle => '覆寫標題';
+}
+
+class TestMaterialApp extends StatelessWidget {
+  final Locale locale;
+  final LocalizationsDelegate? localizationsOverride;
+  final String Function(BuildContext context) localizedText;
```
Comment (lesnitsky) [inline packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart:147]: `localizedText` sounds more like a data property, not a function, maybe `localizeText` is a better name

File: packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+
+  const TestMaterialApp({
+    super.key,
+    required this.locale,
+    this.localizationsOverride,
+    required this.localizedText,
+  });
+
+  @override
+  Widget build(BuildContext context) => MaterialApp(
```
Comment (lesnitsky) [inline packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart:157]: convert to block body

**Review by lesnitsky — CHANGES_REQUESTED** [review]

**Comment by lesnitsky** [comment]
@gary6lin could you please run `melos run format` to make `code_health/format` green.

**Review by lesnitsky — CHANGES_REQUESTED** [review]

File: packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart [hunk 5]
```diff
@@ -0,0 +1,177 @@
...
+const localeZh = Locale('zh');
+const localeTW = Locale('zh', 'TW');
+
+Future<void> main() async {
+  late FirebaseUILocalizationDelegate delegate;
+
+  group(
+    'FirebaseUILocalization loads the appropriate Chinese translation',
+    () {
+      localizedText(BuildContext context) =>
```
[the remark this answers is not in the document]
Comment (gary6lin) [reply packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart:20]: Sure thing :)
Btw, do you have any tips for using block or expression body? Cus I use the expression body quite often.
I only use the block body if I find the result of `dart format` is too ugly.

[the remark this answers is not in the document]
Comment (lesnitsky) [reply packages/firebase_ui_localizations/test/firebase_ui_localizations_test.dart]: I prefer using block body when expression doesn't fit a single line and actual body gets moved to the next line

**Review by lesnitsky — APPROVED** [review]
